version: '3.8'

services:
  public-pool:
    container_name: public-pool
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"        
    ports:
      - "127.0.0.1:3333:3333/tcp"
      - "127.0.0.1:3334:3334/tcp"
    volumes:
      - "./.env:/public-pool/.env:ro"
    environment:
      - NODE_ENV=production

